import logging
from datetime import datetime, timezone
from typing import List, Dict, Any

logger = logging.getLogger("SeedBuyers")

DEMO_BUYER_REQUIREMENTS: List[Dict[str, Any]] = [
    # --- POTTERY & TERRACOTTA ---
    {
        "buyer_id": "BUYER-MUM-PRM-001",
        "buyer_name": "Ananya Sharma",
        "organization_name": "Parampara Heritage Retail",
        "display_name": "Parampara Heritage Retail",
        "buyer_type": "Boutique / Retailer",
        "categories": ["pottery_terracotta"],
        "budget_min": 1500,
        "budget_max": 2500,
        "quantity_min": 10,
        "quantity_max": 100,
        "material_preferences": ["terracotta clay", "clay", "natural clay", "earthenware"],
        "craft_preferences": ["Rajasthani Terracotta Art", "Terracotta Pottery", "Clay Craft", "Bankura Terracotta"],
        "region_preferences": ["Rajasthan", "West Bengal", "Gujarat"],
        "description": "Curated collection of artisanal earthen cookware and decorative terracotta planters for boutique retail.",
        "demo_data": True,
        "status": "active",
    },
    {
        "buyer_id": "BUYER-BLR-SYA-002",
        "buyer_name": "Vikramaditya Nair",
        "organization_name": "Shunya Organics & Cafe",
        "display_name": "Shunya Organics & Cafe",
        "buyer_type": "Hospitality Buyer",
        "categories": ["pottery_terracotta"],
        "budget_min": 200,
        "budget_max": 550,
        "quantity_min": 50,
        "quantity_max": 300,
        "material_preferences": ["terracotta", "clay", "earthen"],
        "craft_preferences": ["Handmade Earthen Pottery", "Pottery"],
        "region_preferences": ["North India", "Rajasthan", "Uttar Pradesh"],
        "description": "Eco-friendly natural cooling terracotta water pots, jugs, and serveware for farm-to-table restaurants.",
        "demo_data": True,
        "status": "active",
    },
    {
        "buyer_id": "BUYER-DEL-MVD-003",
        "buyer_name": "Ritu Dalmia",
        "organization_name": "Mridang Home & Living",
        "display_name": "Mridang Home & Living",
        "buyer_type": "Home Decor Buyer",
        "categories": ["pottery_terracotta", "painting_folk"],
        "budget_min": 1200,
        "budget_max": 4500,
        "quantity_min": 10,
        "quantity_max": 50,
        "material_preferences": ["blue pottery", "glazed ceramic", "terracotta"],
        "craft_preferences": ["Jaipur Blue Pottery", "Terracotta Sculpture"],
        "region_preferences": ["Rajasthan"],
        "description": "Statement artisan vases, wall plates, and handcrafted studio pottery for luxury urban residences.",
        "demo_data": True,
        "status": "active",
    },

    # --- TEXTILE HANDLOOM ---
    {
        "buyer_id": "BUYER-HYD-SVK-004",
        "buyer_name": "Sunita Reddy",
        "organization_name": "Sattva Ethnic Weaves",
        "display_name": "Sattva Ethnic Weaves",
        "buyer_type": "Boutique / Retailer",
        "categories": ["textile_handloom"],
        "budget_min": 1800,
        "budget_max": 6500,
        "quantity_min": 15,
        "quantity_max": 80,
        "material_preferences": ["cotton", "mulberry silk", "tussar silk", "khadi"],
        "craft_preferences": ["Chanderi Weaving", "Banarasi Handloom", "Ikat Weave", "Sambalpuri Handloom", "Handloom Weaving"],
        "region_preferences": ["Madhya Pradesh", "Uttar Pradesh", "Odisha", "Telangana"],
        "description": "Authentic certified handloom sarees, dupattas, and unstitched suit fabric sets for premium retail showrooms.",
        "demo_data": True,
        "status": "active",
    },
    {
        "buyer_id": "BUYER-MUM-VYA-005",
        "buyer_name": "Arjun Kapoor",
        "organization_name": "Vayu Sustainable Fashion Exporters",
        "display_name": "Vayu Sustainable Fashion Exporters",
        "buyer_type": "Exporter",
        "categories": ["textile_handloom", "textile_embroidery"],
        "budget_min": 2500,
        "budget_max": 9000,
        "quantity_min": 30,
        "quantity_max": 150,
        "material_preferences": ["organic cotton", "linen", "pashmina", "silk"],
        "craft_preferences": ["Handwoven Khadi", "Kullu Handloom", "Pochampally Ikat"],
        "region_preferences": ["Kashmir", "Himachal Pradesh", "Andhra Pradesh"],
        "description": "Zero-carbon ethical slow fashion line featuring hand-spun indigenous fibers for export to EU conscious markets.",
        "demo_data": True,
        "status": "active",
    },
    {
        "buyer_id": "BUYER-BLR-LST-006",
        "buyer_name": "Priya Chandrasekhar",
        "organization_name": "Loom & Stone Hospitality Linens",
        "display_name": "Loom & Stone Hospitality Linens",
        "buyer_type": "Hospitality Buyer",
        "categories": ["textile_handloom"],
        "budget_min": 800,
        "budget_max": 2200,
        "quantity_min": 100,
        "quantity_max": 500,
        "material_preferences": ["pure cotton", "coarse cotton", "linen"],
        "craft_preferences": ["Handloom Bedspread Weaving", "Durrie Weaving"],
        "region_preferences": ["Haryana", "Rajasthan", "Tamil Nadu"],
        "description": "Handwoven throws, durable room bedcovers, and artisan table runners for boutique heritage resort chain.",
        "demo_data": True,
        "status": "active",
    },

    # --- TEXTILE EMBROIDERY ---
    {
        "buyer_id": "BUYER-LKO-RVA-007",
        "buyer_name": "Zoya Siddiqui",
        "organization_name": "Rivayat Bridal Couture",
        "display_name": "Rivayat Bridal Couture",
        "buyer_type": "Boutique / Retailer",
        "categories": ["textile_embroidery"],
        "budget_min": 3500,
        "budget_max": 15000,
        "quantity_min": 5,
        "quantity_max": 30,
        "material_preferences": ["silk", "georgette", "organza", "velvet"],
        "craft_preferences": ["Chikankari Hand Embroidery", "Zardozi Craft", "Kashmiri Aari", "Phulkari Embroidery"],
        "region_preferences": ["Uttar Pradesh", "Punjab", "Jammu & Kashmir"],
        "description": "Intricate hand-embroidered heritage stoles, bridal lehenga panels, and festive occasion shawls.",
        "demo_data": True,
        "status": "active",
    },
    {
        "buyer_id": "BUYER-KOL-KMT-008",
        "buyer_name": "Debasree Roy",
        "organization_name": "Kolkata Motifs Souvenirs",
        "display_name": "Kolkata Motifs Souvenirs",
        "buyer_type": "Handicraft Store",
        "categories": ["textile_embroidery", "basketry_bamboo"],
        "budget_min": 450,
        "budget_max": 1400,
        "quantity_min": 50,
        "quantity_max": 250,
        "material_preferences": ["cotton", "jute", "canvas"],
        "craft_preferences": ["Kantha Stitch Art", "Suf Embroidery", "Rabari Mirror Work"],
        "region_preferences": ["West Bengal", "Gujarat"],
        "description": "Handmade embroidered tote bags, cosmetic pouches, and decorative table mats for museum gift shops.",
        "demo_data": True,
        "status": "active",
    },

    # --- WOODCRAFT ---
    {
        "buyer_id": "BUYER-DEL-KAS-009",
        "buyer_name": "Kabir Mehta",
        "organization_name": "Kastha Woodcraft & Living",
        "display_name": "Kastha Woodcraft & Living",
        "buyer_type": "Home Decor Buyer",
        "categories": ["woodcraft"],
        "budget_min": 750,
        "budget_max": 3200,
        "quantity_min": 20,
        "quantity_max": 100,
        "material_preferences": ["sheesham wood", "teak wood", "rosewood", "mango wood"],
        "craft_preferences": ["Saharanpur Wood Carving", "Jali Woodcraft", "Hand Carved Wood"],
        "region_preferences": ["Uttar Pradesh", "Karnataka", "Kerala"],
        "description": "Hand-carved wooden platters, spice storage boxes, bookends, and lattice desk organizers.",
        "demo_data": True,
        "status": "active",
    },
    {
        "buyer_id": "BUYER-MAA-AAR-010",
        "buyer_name": "Lakshmi Sundaram",
        "organization_name": "Aaroh Wooden Toys & Learning",
        "display_name": "Aaroh Wooden Toys & Learning",
        "buyer_type": "Institutional Procurement",
        "categories": ["woodcraft"],
        "budget_min": 250,
        "budget_max": 950,
        "quantity_min": 100,
        "quantity_max": 1000,
        "material_preferences": ["ivory wood", "hale wood", "softwood", "natural lac dyes"],
        "craft_preferences": ["Channapatna Wooden Toys", "Natural Lacquer Craft"],
        "region_preferences": ["Karnataka", "Andhra Pradesh"],
        "description": "Non-toxic organic wooden learning toys, spinning tops, and stacking blocks for preschool chains.",
        "demo_data": True,
        "status": "active",
    },
    {
        "buyer_id": "BUYER-MUM-VAR-011",
        "buyer_name": "Varun Malhotra",
        "organization_name": "Vastu Design & Architectural Studio",
        "display_name": "Vastu Design & Architectural Studio",
        "buyer_type": "Home Decor Buyer",
        "categories": ["woodcraft", "metalcraft"],
        "budget_min": 4000,
        "budget_max": 20000,
        "quantity_min": 5,
        "quantity_max": 25,
        "material_preferences": ["solid teak", "brass inlays", "walnut wood"],
        "craft_preferences": ["Tarkashi Wood Inlay", "Kashmiri Walnut Carving"],
        "region_preferences": ["Rajasthan", "Jammu & Kashmir"],
        "description": "Bespoke brass-inlaid console mirrors, carved screen dividers, and custom wooden statement art.",
        "demo_data": True,
        "status": "active",
    },

    # --- METALCRAFT ---
    {
        "buyer_id": "BUYER-BHO-GTM-012",
        "buyer_name": "Dr. S. K. Mahapatra",
        "organization_name": "Gautam Heritage Trust & Museum",
        "display_name": "Gautam Heritage Trust & Museum",
        "buyer_type": "Cultural Institution",
        "categories": ["metalcraft"],
        "budget_min": 1500,
        "budget_max": 8000,
        "quantity_min": 10,
        "quantity_max": 60,
        "material_preferences": ["brass", "bronze", "copper", "bell metal"],
        "craft_preferences": ["Dhokra Lost-Wax Casting", "Moradabad Brass Art", "Panchaloha Casting"],
        "region_preferences": ["Chhattisgarh", "Odisha", "Uttar Pradesh", "Tamil Nadu"],
        "description": "Lost-wax cast tribal bronze figurines, hanging oil lamps (diyas), and traditional bell metal tableware.",
        "demo_data": True,
        "status": "active",
    },
    {
        "buyer_id": "BUYER-GUG-ENT-013",
        "buyer_name": "Meera Deshmukh",
        "organization_name": "Enterprise Elegance Gifting",
        "display_name": "Enterprise Elegance Gifting",
        "buyer_type": "Corporate Gifting",
        "categories": ["metalcraft", "woodcraft"],
        "budget_min": 600,
        "budget_max": 1800,
        "quantity_min": 100,
        "quantity_max": 1500,
        "material_preferences": ["brass", "bidri metal", "copper", "wood"],
        "craft_preferences": ["Bidriware Inlay", "Brass Etching", "Metal Craft"],
        "region_preferences": ["Karnataka", "Telangana", "Maharashtra"],
        "description": "Executive corporate gift hampers: engraved brass pen holders, Bidri coin trays, and artisan card cases.",
        "demo_data": True,
        "status": "active",
    },

    # --- JEWELLERY ---
    {
        "buyer_id": "BUYER-BBU-RUP-014",
        "buyer_name": "Rajeshwari Patnaik",
        "organization_name": "Rupa Silver Filigree Gallery",
        "display_name": "Rupa Silver Filigree Gallery",
        "buyer_type": "Boutique / Retailer",
        "categories": ["jewellery"],
        "budget_min": 500,
        "budget_max": 3500,
        "quantity_min": 20,
        "quantity_max": 120,
        "material_preferences": ["sterling silver", "brass", "semi-precious stones", "tribal silver"],
        "craft_preferences": ["Silver Filigree (Tarakasi)", "Tribal Silver Jewellery", "Kundan Meenakari"],
        "region_preferences": ["Odisha", "Rajasthan", "Gujarat"],
        "description": "Handmade silver filigree ear cuffs, tribal choker necklaces, and semi-precious stone statement rings.",
        "demo_data": True,
        "status": "active",
    },
    {
        "buyer_id": "BUYER-AMD-ECO-015",
        "buyer_name": "Siddharth Shah",
        "organization_name": "EcoWear Jewellery Exporters",
        "display_name": "EcoWear Jewellery Exporters",
        "buyer_type": "Exporter",
        "categories": ["jewellery", "basketry_bamboo"],
        "budget_min": 250,
        "budget_max": 950,
        "quantity_min": 80,
        "quantity_max": 400,
        "material_preferences": ["terracotta", "fabric", "natural seeds", "jute", "bamboo"],
        "craft_preferences": ["Terracotta Jewellery", "Fabric Jewellery", "Beadwork"],
        "region_preferences": ["West Bengal", "Assam", "Tamil Nadu"],
        "description": "Eco-friendly terracotta hand-painted pendants and upcycled fabric tassel earrings for ethical fashion boutiques.",
        "demo_data": True,
        "status": "active",
    },

    # --- BASKETRY & BAMBOO ---
    {
        "buyer_id": "BUYER-GAU-PRK-016",
        "buyer_name": "Biren Kalita",
        "organization_name": "Prakriti Cane & Bamboo Crafts",
        "display_name": "Prakriti Cane & Bamboo Crafts",
        "buyer_type": "Handicraft Store",
        "categories": ["basketry_bamboo"],
        "budget_min": 300,
        "budget_max": 1100,
        "quantity_min": 40,
        "quantity_max": 300,
        "material_preferences": ["bamboo", "cane", "sikki grass", "kauna reed", "jute"],
        "craft_preferences": ["Northeast Bamboo Craft", "Sikki Grass Weaving", "Cane Furniture & Storage"],
        "region_preferences": ["Assam", "Manipur", "Bihar", "Tripura"],
        "description": "Natural woven storage baskets, laundry bins, fruit hampers, and dining table place mats.",
        "demo_data": True,
        "status": "active",
    },
    {
        "buyer_id": "BUYER-BLR-LUM-017",
        "buyer_name": "Neha Joshi",
        "organization_name": "Lumina Hospitality Lighting Solutions",
        "display_name": "Lumina Hospitality Lighting Solutions",
        "buyer_type": "Hospitality Buyer",
        "categories": ["basketry_bamboo", "woodcraft"],
        "budget_min": 900,
        "budget_max": 3800,
        "quantity_min": 15,
        "quantity_max": 80,
        "material_preferences": ["bamboo strips", "cane weave", "rattan"],
        "craft_preferences": ["Bamboo Pendant Lamp Weaving", "Cane Craft"],
        "region_preferences": ["Assam", "Kerala", "West Bengal"],
        "description": "Organic woven wicker pendant lampshades and ceiling diffusers for luxury beach & rainforest eco-resorts.",
        "demo_data": True,
        "status": "active",
    },

    # --- PAINTING & FOLK ART ---
    {
        "buyer_id": "BUYER-DEL-SKS-018",
        "buyer_name": "Dr. Arindam Sen",
        "organization_name": "Sanskriti Kala Akademi Foundation",
        "display_name": "Sanskriti Kala Akademi Foundation",
        "buyer_type": "Cultural Institution",
        "categories": ["painting_folk"],
        "budget_min": 1500,
        "budget_max": 12000,
        "quantity_min": 5,
        "quantity_max": 40,
        "material_preferences": ["handmade paper", "tussar silk canvas", "natural mineral pigments", "cotton cloth"],
        "craft_preferences": ["Madhubani Painting", "Pattachitra Art", "Warli Art", "Gond Painting", "Pichwai Art"],
        "region_preferences": ["Bihar", "Odisha", "Maharashtra", "Madhya Pradesh", "Rajasthan"],
        "description": "Authentic master-artisan folk paintings depicting mythology and flora/fauna using natural vegetable dyes.",
        "demo_data": True,
        "status": "active",
    },
    {
        "buyer_id": "BUYER-HYD-KAL-019",
        "buyer_name": "Madhuri Varma",
        "organization_name": "KalaKriti Modern Folk Art Gallery",
        "display_name": "KalaKriti Modern Folk Art Gallery",
        "buyer_type": "Home Decor Buyer",
        "categories": ["painting_folk", "woodcraft"],
        "budget_min": 800,
        "budget_max": 3500,
        "quantity_min": 10,
        "quantity_max": 60,
        "material_preferences": ["canvas", "wood board", "handmade paper"],
        "craft_preferences": ["Warli Folk Art", "Kalamkari Painting", "Gond Art"],
        "region_preferences": ["Maharashtra", "Andhra Pradesh", "Madhya Pradesh"],
        "description": "Framed folk canvas art and wooden handpainted decorative wall clocks for contemporary interior design.",
        "demo_data": True,
        "status": "active",
    },

    # --- MULTI-CATEGORY EXPORT & INSTITUTIONAL ---
    {
        "buyer_id": "BUYER-MUM-IND-020",
        "buyer_name": "Anand Singhania",
        "organization_name": "Indus Craft Exporters India Ltd.",
        "display_name": "Indus Craft Exporters India Ltd.",
        "buyer_type": "Exporter",
        "categories": ["textile_handloom", "metalcraft", "woodcraft", "pottery_terracotta"],
        "budget_min": 1000,
        "budget_max": 7500,
        "quantity_min": 50,
        "quantity_max": 500,
        "material_preferences": ["silk", "brass", "sheesham wood", "terracotta"],
        "craft_preferences": ["GI Certified Handlooms", "Handcrafted Metalware", "Traditional Woodcraft"],
        "region_preferences": ["Rajasthan", "Uttar Pradesh", "Odisha", "Tamil Nadu"],
        "description": "Consolidated multi-category handicraft shipments for high-end diaspora department stores worldwide.",
        "demo_data": True,
        "status": "active",
    },
    {
        "buyer_id": "BUYER-DEL-GKV-021",
        "buyer_name": "Ramesh Chand",
        "organization_name": "Gramin Kala Vikas State Emporia Network",
        "display_name": "Gramin Kala Vikas State Emporia Network",
        "buyer_type": "Institutional Procurement",
        "categories": ["textile_handloom", "textile_embroidery", "jewellery", "painting_folk"],
        "budget_min": 600,
        "budget_max": 5000,
        "quantity_min": 30,
        "quantity_max": 200,
        "material_preferences": ["cotton", "silk", "silver", "handmade paper"],
        "craft_preferences": ["Handloom", "Embroidery", "Silver Filigree", "Folk Art"],
        "region_preferences": ["All India"],
        "description": "State-level procurement network sourcing genuine certified master-artisan creations for retail emporiums.",
        "demo_data": True,
        "status": "active",
    },
    {
        "buyer_id": "BUYER-PUN-UTS-022",
        "buyer_name": "Neeraja Kulkarni",
        "organization_name": "Utsav Festive Gifting Solutions",
        "display_name": "Utsav Festive Gifting Solutions",
        "buyer_type": "Corporate Gifting",
        "categories": ["pottery_terracotta", "jewellery", "basketry_bamboo"],
        "budget_min": 300,
        "budget_max": 1200,
        "quantity_min": 100,
        "quantity_max": 2000,
        "material_preferences": ["terracotta", "brass", "bamboo", "jute"],
        "craft_preferences": ["Terracotta Diya Making", "Handmade Brass Keepsakes", "Bamboo Packaging"],
        "region_preferences": ["Rajasthan", "Uttar Pradesh", "Assam"],
        "description": "Diwali and festive corporate hampers combining handcrafted diyas, artisanal sweets packaging, and brass tokens.",
        "demo_data": True,
        "status": "active",
    },
    {
        "buyer_id": "BUYER-JAI-RAA-023",
        "buyer_name": "Maharani Gayatri Devi Trust",
        "organization_name": "Raas Heritage Hotels & Resorts",
        "display_name": "Raas Heritage Hotels & Resorts",
        "buyer_type": "Hospitality Buyer",
        "categories": ["painting_folk", "metalcraft", "textile_handloom"],
        "budget_min": 2000,
        "budget_max": 18000,
        "quantity_min": 5,
        "quantity_max": 40,
        "material_preferences": ["brass", "pure silk", "natural pigments", "teak"],
        "craft_preferences": ["Pichwai Painting", "Moradabad Brass", "Banarasi Brocade"],
        "region_preferences": ["Rajasthan", "Uttar Pradesh", "Madhya Pradesh"],
        "description": "Luxury palace hotel suites renovation seeking museum-grade traditional textiles, paintings, and brass lamps.",
        "demo_data": True,
        "status": "active",
    },
    {
        "buyer_id": "BUYER-COI-GRM-024",
        "buyer_name": "K. Ramaswamy",
        "organization_name": "Gramodyog Artisan Village Collective",
        "display_name": "Gramodyog Artisan Village Collective",
        "buyer_type": "Handicraft Store",
        "categories": ["pottery_terracotta", "basketry_bamboo", "woodcraft"],
        "budget_min": 200,
        "budget_max": 900,
        "quantity_min": 30,
        "quantity_max": 150,
        "material_preferences": ["clay", "cane", "bamboo", "wood"],
        "craft_preferences": ["Traditional Pottery", "Bamboo Weaving", "Wood Turnery"],
        "region_preferences": ["South India", "Karnataka", "Tamil Nadu", "Kerala"],
        "description": "Community retail marketplace dedicated to everyday utilitarian crafts and sustainable home essentials.",
        "demo_data": True,
        "status": "active",
    },
    {
        "buyer_id": "BUYER-BLR-BAN-025",
        "buyer_name": "Maya Rao",
        "organization_name": "Banjara Nomadic Studio",
        "display_name": "Banjara Nomadic Studio",
        "buyer_type": "Boutique / Retailer",
        "categories": ["textile_embroidery", "jewellery"],
        "budget_min": 1200,
        "budget_max": 4800,
        "quantity_min": 15,
        "quantity_max": 75,
        "material_preferences": ["cotton silk", "linen", "silver", "glass beads"],
        "craft_preferences": ["Lambani Embroidery", "Mirror Work", "Bead Jewellery"],
        "region_preferences": ["Karnataka", "Gujarat", "Rajasthan"],
        "description": "Indie designer label integrating tribal nomadic embroidery and handcrafted accessories into urban streetwear.",
        "demo_data": True,
        "status": "active",
    }
]

async def seed_buyer_requirements(db, overwrite: bool = False) -> int:
    """
    Seeds the buyer_requirements collection deterministically with demo market requirements.
    """
    from app.db.collections import BUYER_REQUIREMENTS_COLLECTION
    
    coll = db[BUYER_REQUIREMENTS_COLLECTION]
    
    count = await coll.count_documents({})
    if count > 0 and not overwrite:
        logger.info(f"Buyer requirements already seeded ({count} documents present). Skipping.")
        return count

    if overwrite:
        await coll.delete_many({})
        logger.info("Cleared existing buyer requirements collection.")

    now_iso = datetime.now(timezone.utc).isoformat()
    docs = []
    for item in DEMO_BUYER_REQUIREMENTS:
        doc = dict(item)
        doc["created_at"] = now_iso
        doc["updated_at"] = now_iso
        docs.append(doc)

    result = await coll.insert_many(docs)
    inserted_count = len(result.inserted_ids)
    logger.info(f"Successfully seeded {inserted_count} deterministic demo buyer requirements.")
    return inserted_count
