import React from 'react'
import { useTranslation } from 'react-i18next'
import { 
  SealCheck, 
  Package, 
  Clock, 
  Certificate, 
  Ruler, 
  Buildings, 
  Palette, 
  DownloadSimple, 
  WhatsappLogo,
  ChatText,
  ArrowSquareOut
} from '@phosphor-icons/react'
import { getWhatsAppInquiryUrl, getSmsInquiryUrl, isValidPhoneNumber } from '../config/inquiryMessage'

export default function WholesaleSheetCard({
  listing = {},
  artisan = {},
  whatsappNumber = '+919556828397',
  onDownloadPdf,
  className = '',
}) {
  const { t } = useTranslation()
  const { language } = useLanguageStore()

  // Base pricing calculations
  const unitPrice = Number(listing.price) || 1939
  const tier1Price = Math.round(unitPrice)
  const tier2Price = Math.round(unitPrice * 0.85)
  const tier3Price = Math.round(unitPrice * 0.72)

  const tier1Total = (tier1Price * 10).toLocaleString('en-IN')
  const tier2Total = (tier2Price * 50).toLocaleString('en-IN')

  // Product defaults
  const backendBase = (import.meta.env.VITE_API_URL || 'http://localhost:8000').replace(/\/$/, '')
  const productTitle = listing.title || 'Handcrafted Terracotta Heritage Pot'
  const productCategory = listing.category || 'Pottery and Terracotta'
  let productImage = listing.image || '/demo/enhanced_pottery.jpg'
  if (productImage.startsWith('/v1/media/') || productImage.startsWith('v1/media/')) {
    productImage = `${backendBase}/${productImage.replace(/^\//, '')}`
  } else if (productImage.startsWith('/temp/') || productImage.startsWith('temp/')) {
    productImage = `${backendBase}/${productImage.replace(/^\//, '')}`
  }

  // Artisan defaults
  const artisanName = artisan.name || 'Rameshwar Prajapati'
  const artisanRegion = artisan.region || 'Jaipur, Rajasthan'
  const artisanYears = artisan.yearsActive || '18 years'
  const artisanId = artisan.artisanId || 'KG-2024-8921'
  const effectivePhone = artisan.phone || listing.artisan_phone || whatsappNumber || (artisanId === 'KG-2024-8921' ? '+919556828397' : '')
  const hasValidPhone = isValidPhoneNumber(effectivePhone)

  // Build inquiry URLs
  const waUrl = hasValidPhone
    ? getWhatsAppInquiryUrl({
        artisanPhone: effectivePhone,
        artisanName,
        productTitle,
        quantity: 20,
        productUrl: typeof window !== 'undefined' ? window.location.href : '',
        language,
      })
    : null

  const smsUrl = hasValidPhone
    ? getSmsInquiryUrl({
        artisanPhone: effectivePhone,
        artisanName,
        productTitle,
        quantity: 20,
        productUrl: typeof window !== 'undefined' ? window.location.href : '',
        language,
      })
    : null

  return (
    <div className={`wholesale-doc w-full max-w-3xl mx-auto p-6 sm:p-8 bg-white text-stone-900 shadow-sm rounded-lg border border-stone-200 ${className}`}>
      
      {/* Top Document Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between border-b border-stone-200 pb-5 mb-6 gap-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="text-[10px] font-semibold uppercase tracking-wider text-amber-900 bg-amber-50 border border-amber-200 px-2 py-0.5 rounded">
              {t('screen.b2b_spec')}
            </span>
            <span className="text-xs text-stone-500 font-mono">
              ID: {listing.id || 'LST-8921'}
            </span>
          </div>
          <h1 className="text-xl sm:text-2xl font-semibold text-stone-900">
            {t('wholesale.doc_title', 'B2B Wholesale Inquiry & Spec Sheet')}
          </h1>
          <p className="text-xs text-stone-500 mt-0.5">
            {t('wholesale.doc_subtitle', 'Official artisan wholesale catalog generated by KarigaarAI')}
          </p>
        </div>

        {/* Verified Badge */}
        <div className="flex items-center gap-1.5 px-2.5 py-1 rounded bg-emerald-50 border border-emerald-200 text-emerald-800 self-start sm:self-center">
          <SealCheck size={16} weight="fill" className="text-emerald-700" />
          <span className="text-xs font-semibold tracking-wide">
            {t('wholesale.verified_artisan', 'Verified Artisan')}
          </span>
        </div>
      </div>

      {/* SECTION 1 — Product Header */}
      <section className="mb-6">
        <h2 className="text-[11px] font-semibold text-stone-500 uppercase tracking-widest mb-2.5">
          {t('screen.section_product', 'Section 1 · Product Information')}
        </h2>
        <div className="flex flex-col sm:flex-row gap-5 items-start bg-stone-50 p-4 rounded border border-stone-200">
          <div className="w-full sm:w-36 h-36 rounded overflow-hidden bg-stone-100 shrink-0 border border-stone-200">
            <img
              src={productImage}
              alt={productTitle}
              className="w-full h-full object-cover"
              onError={(e) => {
                e.target.onerror = null
                e.target.src = 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=600&q=80'
              }}
            />
          </div>

          <div className="flex-1">
            <span className="inline-block text-[11px] font-semibold text-amber-800 uppercase tracking-wider mb-1">
              {productCategory}
            </span>
            <h3 className="text-lg font-semibold text-stone-900 mb-1.5 leading-snug">
              {productTitle}
            </h3>
            <p className="text-xs text-stone-600 mb-3 leading-relaxed">
              {listing.description || t('screen.published_catalog')}
            </p>

            <div className="flex flex-wrap gap-y-1 gap-x-4 text-xs text-stone-600 border-t border-stone-200 pt-2.5">
              <div>
                <span className="text-stone-500">{t('screen.artisan')}: </span>
                <strong className="text-stone-900">{artisanName}</strong>
              </div>
              <div>
                <span className="text-stone-500">{t('screen.origin')}: </span>
                <strong className="text-stone-900">{artisanRegion}</strong>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* SECTION 2 — Bulk Pricing Table */}
      <section className="mb-6">
        <div className="flex items-center justify-between mb-2">
          <h2 className="text-[11px] font-semibold text-stone-500 uppercase tracking-widest">
            {t('screen.section_pricing')}
          </h2>
          <span className="text-xs text-stone-500">
            {t('screen.base_retail')}: <strong className="font-mono text-stone-900">₹{unitPrice}</strong>
          </span>
        </div>

        <div className="overflow-x-auto rounded border border-stone-200">
          <table className="w-full text-left">
            <thead>
              <tr className="bg-stone-100 text-stone-700 text-[11px] uppercase font-semibold tracking-wider">
                <th className="py-2.5 px-3.5">{t('wholesale.tier_quantity', 'Quantity Tier')}</th>
                <th className="py-2.5 px-3.5">{t('wholesale.tier_price', 'Price per Unit')}</th>
                <th className="py-2.5 px-3.5">{t('wholesale.tier_total', 'Total Est.')}</th>
                <th className="py-2.5 px-3.5 text-right">{t('screen.discount')}</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-stone-200 text-xs">
              <tr className="hover:bg-stone-50">
                <td className="py-2.5 px-3.5 font-medium text-stone-900">10–49 {t('screen.units', 'units')}</td>
                <td className="py-2.5 px-3.5 font-mono font-semibold text-stone-900">₹{tier1Price}</td>
                <td className="py-2.5 px-3.5 text-stone-600 font-mono">₹{tier1Total} <span className="text-[10px] text-stone-400 font-sans">({t('screen.for_units', { count: 10 })})</span></td>
                <td className="py-2.5 px-3.5 text-right text-stone-500">{t('screen.standard_b2b')}</td>
              </tr>
              <tr className="hover:bg-stone-50 bg-stone-50/50">
                <td className="py-2.5 px-3.5 font-medium text-stone-900">50–99 {t('screen.units', 'units')}</td>
                <td className="py-2.5 px-3.5 font-mono font-semibold text-stone-900">₹{tier2Price}</td>
                <td className="py-2.5 px-3.5 text-stone-600 font-mono">₹{tier2Total} <span className="text-[10px] text-stone-400 font-sans">({t('screen.for_units', { count: 50 })})</span></td>
                <td className="py-2.5 px-3.5 text-right font-semibold text-emerald-700">15% {t('screen.off')}</td>
              </tr>
              <tr className="hover:bg-stone-50">
                <td className="py-2.5 px-3.5 font-medium text-stone-900">100+ {t('screen.units', 'units')}</td>
                <td className="py-2.5 px-3.5 font-mono font-semibold text-emerald-700">₹{tier3Price}</td>
                <td className="py-2.5 px-3.5 font-semibold text-stone-900">
                  {t('wholesale.contact_us', 'Contact us for custom quota')}
                </td>
                <td className="py-2.5 px-3.5 text-right font-semibold text-emerald-700">28% {t('screen.off')}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      {/* SECTION 3 — Product Specifications */}
      <section className="mb-6">
        <h2 className="text-[11px] font-semibold text-stone-500 uppercase tracking-widest mb-2.5">
          {t('screen.section_specs')}
        </h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs">
          <div className="p-2.5 rounded border border-stone-200 bg-stone-50 flex items-start gap-2.5">
            <Palette size={16} className="text-stone-600 shrink-0 mt-0.5" />
            <div>
              <span className="text-[10px] text-stone-500 block uppercase font-semibold">{t('wholesale.spec_craft', 'Craft Type')}</span>
              <strong className="text-stone-900 font-medium">{listing.craftType || productCategory}</strong>
            </div>
          </div>

          <div className="p-2.5 rounded border border-stone-200 bg-stone-50 flex items-start gap-2.5">
            <Package size={16} className="text-stone-600 shrink-0 mt-0.5" />
            <div>
              <span className="text-[10px] text-stone-500 block uppercase font-semibold">{t('wholesale.spec_material', 'Material')}</span>
              <strong className="text-stone-900 font-medium">{listing.material || t('screen.material')}</strong>
            </div>
          </div>

          <div className="p-2.5 rounded border border-stone-200 bg-stone-50 flex items-start gap-2.5">
            <Buildings size={16} className="text-stone-600 shrink-0 mt-0.5" />
            <div>
              <span className="text-[10px] text-stone-500 block uppercase font-semibold">{t('wholesale.spec_technique', 'Technique')}</span>
              <strong className="text-stone-900 font-medium">{listing.technique || t('screen.craft_tradition')}</strong>
            </div>
          </div>

          <div className="p-2.5 rounded border border-stone-200 bg-stone-50 flex items-start gap-2.5">
            <Ruler size={16} className="text-stone-600 shrink-0 mt-0.5" />
            <div>
              <span className="text-[10px] text-stone-500 block uppercase font-semibold">{t('wholesale.spec_dimensions', 'Dimensions')}</span>
              <strong className="text-stone-900 font-medium">{listing.dimensions || t('screen.minimum_order')}</strong>
            </div>
          </div>

          <div className="p-2.5 rounded border border-stone-200 bg-stone-50 flex items-start gap-2.5">
            <Clock size={16} className="text-stone-600 shrink-0 mt-0.5" />
            <div>
              <span className="text-[10px] text-stone-500 block uppercase font-semibold">{t('wholesale.spec_lead_time', 'Lead Time')}</span>
              <strong className="text-stone-900 font-medium">{listing.leadTime || t('screen.delivery_time')}</strong>
            </div>
          </div>

          <div className="p-2.5 rounded border border-stone-200 bg-stone-50 flex items-start gap-2.5">
            <Certificate size={16} className="text-stone-600 shrink-0 mt-0.5" />
            <div>
              <span className="text-[10px] text-stone-500 block uppercase font-semibold">{t('wholesale.spec_gi_tag', 'GI Tag Status')}</span>
              <strong className="text-stone-900 font-medium">{listing.giTag || t('screen.verified')}</strong>
            </div>
          </div>
        </div>
      </section>

      {/* SECTION 4 — Artisan Details */}
      <section className="mb-6 p-4 rounded border border-stone-200 bg-stone-50 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="text-[10px] font-semibold uppercase tracking-wider text-stone-700">
              {t('wholesale.artisan_details', 'Artisan Information')}
            </span>
            <span className="px-1.5 py-0.5 rounded text-[10px] font-semibold bg-emerald-50 text-emerald-800 border border-emerald-200">
              {t('screen.verified')}
            </span>
          </div>
          <h4 className="text-base font-semibold text-stone-900">
            {artisanName}
          </h4>
          <p className="text-xs text-stone-600">
            {artisanRegion} · {artisanYears}
          </p>
        </div>

        <div className="text-left sm:text-right border-t sm:border-t-0 border-stone-200 pt-2 sm:pt-0 w-full sm:w-auto">
          <span className="text-[10px] text-stone-500 uppercase font-semibold block">{t('screen.artisan_id')}:</span>
          <span className="font-mono text-xs font-semibold text-stone-900 bg-white px-2 py-0.5 rounded border border-stone-300 inline-block">
            {artisanId}
          </span>
        </div>
      </section>

      {/* SECTION 5 — Call to Action Buttons (no-print) */}
      <section id="wholesale-actions" className="no-print pt-4 border-t border-stone-200 grid grid-cols-1 sm:grid-cols-3 gap-2 sm:gap-3">
        {/* Download PDF Button */}
        <button
          type="button"
          onClick={onDownloadPdf || (() => window.print())}
          className="py-2.5 px-3 rounded border border-stone-800 text-stone-800 hover:bg-stone-100 font-medium text-xs sm:text-sm flex items-center justify-center gap-2 transition-all cursor-pointer"
        >
          <DownloadSimple size={16} weight="bold" />
          <span>{t('wholesale.download_pdf', 'Download PDF')}</span>
        </button>

        {/* Send Inquiry via WhatsApp */}
        {waUrl ? (
          <a
            href={waUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="py-2.5 px-3 rounded bg-[#1f7a47] hover:bg-[#19653a] text-white font-medium text-xs sm:text-sm flex items-center justify-center gap-2 transition-all text-center cursor-pointer"
          >
            <WhatsappLogo size={18} weight="fill" />
            <span>{t('wholesale.send_whatsapp', 'Inquiry via WhatsApp')}</span>
          </a>
        ) : (
          <button
            type="button"
            disabled
            className="py-2.5 px-3 rounded bg-stone-100 text-stone-400 border border-stone-200 font-medium text-xs sm:text-sm flex items-center justify-center gap-2 opacity-60 cursor-not-allowed text-center"
            title={t('buyer.whatsapp_unavailable', 'WhatsApp unavailable for this artisan')}
          >
            <WhatsappLogo size={18} weight="fill" className="text-stone-400" />
            <span>{t('buyer.whatsapp_unavailable', 'WhatsApp Unavailable')}</span>
          </button>
        )}

        {/* Send Inquiry via SMS */}
        {smsUrl ? (
          <a
            href={smsUrl}
            className="py-2.5 px-3 rounded bg-stone-100 hover:bg-stone-200 text-stone-800 border border-stone-300 font-medium text-xs sm:text-sm flex items-center justify-center gap-2 transition-all text-center cursor-pointer"
          >
            <ChatText size={18} weight="bold" className="text-stone-700" />
            <span>{t('buyer.send_sms', 'Send SMS')}</span>
          </a>
        ) : (
          <button
            type="button"
            disabled
            className="py-2.5 px-3 rounded bg-stone-100 text-stone-400 border border-stone-200 font-medium text-xs sm:text-sm flex items-center justify-center gap-2 opacity-60 cursor-not-allowed text-center"
          >
            <ChatText size={18} weight="bold" className="text-stone-400" />
            <span>{t('buyer.send_sms', 'Send SMS')}</span>
          </button>
        )}
      </section>

      {/* Footer Legal */}
      <div className="mt-6 pt-3 border-t border-stone-200 flex flex-col sm:flex-row justify-between text-[11px] text-stone-400 gap-2">
        <span>© KarigaarAI B2B Network · Direct Trade with Artisans</span>
        <span>{t('screen.published_catalog')}</span>
      </div>
    </div>
  )
}
