import React from 'react'
import { useTranslation } from 'react-i18next'
import { 
  SealCheck, 
  Package, 
  Clock, 
  Certificate, 
  Ruler, 
  Buildings, 
  Palette, 
  DownloadSimple, 
  WhatsappLogo,
  ArrowSquareOut
} from '@phosphor-icons/react'

export default function WholesaleSheetCard({
  listing = {},
  artisan = {},
  whatsappNumber = '919876543210',
  onDownloadPdf,
  className = '',
}) {
  const { t } = useTranslation()

  // Base pricing calculations
  const unitPrice = Number(listing.price) || 1939
  const tier1Price = Math.round(unitPrice)
  const tier2Price = Math.round(unitPrice * 0.85)
  const tier3Price = Math.round(unitPrice * 0.72)

  const tier1Total = (tier1Price * 10).toLocaleString('en-IN')
  const tier2Total = (tier2Price * 50).toLocaleString('en-IN')

  // Product defaults
  const backendBase = (import.meta.env.VITE_API_URL || 'http://localhost:8000').replace(/\/$/, '')
  const productTitle = listing.title || 'हस्तनिर्मित राजस्थानी मिट्टी का घड़ा (Terracotta Heritage Pot)'
  const productCategory = listing.category || 'मिट्टी और टेराकोटा (Pottery & Terracotta)'
  let productImage = listing.image || '/demo/enhanced_pottery.jpg'
  if (productImage.startsWith('/v1/media/') || productImage.startsWith('v1/media/')) {
    productImage = `${backendBase}/${productImage.replace(/^\//, '')}`
  } else if (productImage.startsWith('/temp/') || productImage.startsWith('temp/')) {
    productImage = `${backendBase}/${productImage.replace(/^\//, '')}`
  }

  // Artisan defaults
  const artisanName = artisan.name || 'रामेश्वर प्रजापति (Rameshwar Prajapati)'
  const artisanRegion = artisan.region || 'जयपुर, राजस्थान (Jaipur, Rajasthan)'
  const artisanYears = artisan.yearsActive || '18 वर्ष (18 Years)'
  const artisanId = artisan.artisanId || 'KG-2024-8921'

  // Build WhatsApp inquiry URL
  const waMessage = `Hello, I'm interested in bulk purchasing ${productTitle} by ${artisanName}. Artisan ID: ${artisanId}. Please share availability.`
  const waUrl = `https://wa.me/${whatsappNumber.replace(/[^0-9]/g, '')}?text=${encodeURIComponent(waMessage)}`

  return (
    <div className={`wholesale-doc w-full max-w-3xl mx-auto p-6 sm:p-10 bg-white text-gray-900 shadow-xl rounded-2xl border border-gray-200 ${className}`}>
      
      {/* Top Document Header / Watermark Strip */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between border-b border-gray-200 pb-6 mb-6 gap-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="text-xs font-black uppercase tracking-wider text-orange-600 bg-orange-50 border border-orange-200 px-2.5 py-0.5 rounded">
              B2B SPEC SHEET
            </span>
            <span className="text-xs font-semibold text-gray-500">
              ID: {listing.id || 'LST-8921'}
            </span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-black text-gray-900 font-heading">
            {t('wholesale.doc_title', 'B2B Wholesale Inquiry & Spec Sheet')}
          </h1>
          <p className="text-xs sm:text-sm text-gray-500 mt-0.5">
            {t('wholesale.doc_subtitle', 'Official artisan wholesale catalog generated by KarigaarAI')}
          </p>
        </div>

        {/* Verified Badge */}
        <div className="flex items-center gap-2 px-3 py-1.5 rounded-full bg-emerald-50 border border-emerald-300 text-emerald-800 self-start sm:self-center">
          <SealCheck size={18} weight="fill" className="text-emerald-600" />
          <span className="text-xs font-bold tracking-wide">
            {t('wholesale.verified_artisan', 'Verified Artisan')}
          </span>
        </div>
      </div>

      {/* SECTION 1 — Product Header */}
      <section className="mb-8">
        <h2 className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-3">
          Section 1 · Product Information
        </h2>
        <div className="flex flex-col sm:flex-row gap-6 items-start bg-gray-50 p-4 sm:p-5 rounded-xl border border-gray-100">
          <div className="w-full sm:w-44 h-44 rounded-lg overflow-hidden bg-gray-200 shrink-0 border border-gray-300 shadow-sm">
            <img
              src={productImage}
              alt={productTitle}
              className="w-full h-full object-cover"
              onError={(e) => {
                e.target.onerror = null
                e.target.src = 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=600&q=80'
              }}
            />
          </div>

          <div className="flex-1">
            <span className="inline-block text-xs font-bold text-orange-600 uppercase tracking-wide mb-1">
              {productCategory}
            </span>
            <h3 className="text-xl sm:text-2xl font-bold text-gray-900 mb-2 leading-snug">
              {productTitle}
            </h3>
            <p className="text-sm text-gray-600 mb-4 leading-relaxed">
              {listing.description || 'Authentic handcrafted heritage artisan item crafted according to traditional indigenous methods. Suitable for boutique hotels, corporate gifting, and direct retail distribution.'}
            </p>

            <div className="flex flex-wrap gap-y-1 gap-x-4 text-xs text-gray-600 border-t border-gray-200/80 pt-3">
              <div>
                <span className="text-gray-400 font-medium">Artisan: </span>
                <strong className="text-gray-800">{artisanName}</strong>
              </div>
              <div>
                <span className="text-gray-400 font-medium">Origin: </span>
                <strong className="text-gray-800">{artisanRegion}</strong>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* SECTION 2 — Bulk Pricing Table */}
      <section className="mb-8">
        <div className="flex items-center justify-between mb-3">
          <h2 className="text-xs font-bold text-gray-400 uppercase tracking-widest">
            Section 2 · Bulk Pricing Tiers
          </h2>
          <span className="text-xs text-gray-500">
            Base Retail Price: <strong className="text-gray-900">₹{unitPrice}</strong>
          </span>
        </div>

        <div className="overflow-x-auto rounded-xl border border-gray-200">
          <table className="w-full text-left">
            <thead>
              <tr className="bg-gray-100 text-gray-700 text-xs uppercase font-bold tracking-wider">
                <th className="py-3 px-4">{t('wholesale.tier_quantity', 'Quantity Tier')}</th>
                <th className="py-3 px-4">{t('wholesale.tier_price', 'Price per Unit')}</th>
                <th className="py-3 px-4">{t('wholesale.tier_total', 'Total Est.')}</th>
                <th className="py-3 px-4 text-right">Discount</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-200 text-sm">
              <tr className="hover:bg-gray-50 transition-colors">
                <td className="py-3.5 px-4 font-semibold text-gray-900">10–49 units</td>
                <td className="py-3.5 px-4 font-bold text-gray-900">₹{tier1Price}</td>
                <td className="py-3.5 px-4 text-gray-600">₹{tier1Total} <span className="text-xs text-gray-400">(for 10 units)</span></td>
                <td className="py-3.5 px-4 text-right text-gray-500 font-medium">Standard B2B</td>
              </tr>
              <tr className="hover:bg-gray-50 transition-colors bg-orange-50/30">
                <td className="py-3.5 px-4 font-semibold text-gray-900">50–99 units</td>
                <td className="py-3.5 px-4 font-bold text-orange-600">₹{tier2Price}</td>
                <td className="py-3.5 px-4 text-gray-600">₹{tier2Total} <span className="text-xs text-gray-400">(for 50 units)</span></td>
                <td className="py-3.5 px-4 text-right font-bold text-emerald-600">15% OFF</td>
              </tr>
              <tr className="hover:bg-gray-50 transition-colors">
                <td className="py-3.5 px-4 font-semibold text-gray-900">100+ units</td>
                <td className="py-3.5 px-4 font-bold text-emerald-700">₹{tier3Price}</td>
                <td className="py-3.5 px-4 font-bold text-orange-600">
                  {t('wholesale.contact_us', 'Contact us for custom quota')}
                </td>
                <td className="py-3.5 px-4 text-right font-bold text-emerald-600">28% OFF</td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      {/* SECTION 3 — Product Specifications */}
      <section className="mb-8">
        <h2 className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-3">
          Section 3 · Technical Specifications
        </h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-sm">
          <div className="p-3.5 rounded-lg border border-gray-200 bg-gray-50/60 flex items-start gap-3">
            <Palette size={20} className="text-orange-600 shrink-0 mt-0.5" />
            <div>
              <span className="text-xs text-gray-500 block">{t('wholesale.spec_craft', 'Craft Type')}</span>
              <strong className="text-gray-900">{listing.craftType || productCategory}</strong>
            </div>
          </div>

          <div className="p-3.5 rounded-lg border border-gray-200 bg-gray-50/60 flex items-start gap-3">
            <Package size={20} className="text-indigo-600 shrink-0 mt-0.5" />
            <div>
              <span className="text-xs text-gray-500 block">{t('wholesale.spec_material', 'Material')}</span>
              <strong className="text-gray-900">{listing.material || 'Natural River Clay & Mineral Glazes'}</strong>
            </div>
          </div>

          <div className="p-3.5 rounded-lg border border-gray-200 bg-gray-50/60 flex items-start gap-3">
            <Buildings size={20} className="text-amber-600 shrink-0 mt-0.5" />
            <div>
              <span className="text-xs text-gray-500 block">{t('wholesale.spec_technique', 'Technique')}</span>
              <strong className="text-gray-900">{listing.technique || 'Hand-thrown on traditional wheel, sun-dried, kiln-fired'}</strong>
            </div>
          </div>

          <div className="p-3.5 rounded-lg border border-gray-200 bg-gray-50/60 flex items-start gap-3">
            <Ruler size={20} className="text-emerald-600 shrink-0 mt-0.5" />
            <div>
              <span className="text-xs text-gray-500 block">{t('wholesale.spec_dimensions', 'Dimensions')}</span>
              <strong className="text-gray-900">{listing.dimensions || 'Standard / Custom available (H: 26cm, Dia: 20cm)'}</strong>
            </div>
          </div>

          <div className="p-3.5 rounded-lg border border-gray-200 bg-gray-50/60 flex items-start gap-3">
            <Clock size={20} className="text-blue-600 shrink-0 mt-0.5" />
            <div>
              <span className="text-xs text-gray-500 block">{t('wholesale.spec_lead_time', 'Lead Time')}</span>
              <strong className="text-gray-900">{listing.leadTime || '3–4 weeks for orders under 50 units'}</strong>
            </div>
          </div>

          <div className="p-3.5 rounded-lg border border-gray-200 bg-gray-50/60 flex items-start gap-3">
            <Certificate size={20} className="text-rose-600 shrink-0 mt-0.5" />
            <div>
              <span className="text-xs text-gray-500 block">{t('wholesale.spec_gi_tag', 'GI Tag Status')}</span>
              <strong className="text-gray-900">{listing.giTag || 'Eligible / Heritage Craft Certified'}</strong>
            </div>
          </div>

          <div className="p-3.5 rounded-lg border border-gray-200 bg-gray-50/60 sm:col-span-2 flex items-start gap-3">
            <Package size={20} className="text-purple-600 shrink-0 mt-0.5" />
            <div>
              <span className="text-xs text-gray-500 block">{t('wholesale.spec_moq', 'Minimum Order Quantity')}</span>
              <strong className="text-gray-900">10 units (Mix of sizes/finishes acceptable on advance request)</strong>
            </div>
          </div>
        </div>
      </section>

      {/* SECTION 4 — Artisan Details */}
      <section className="mb-8 p-4 sm:p-5 rounded-xl border border-emerald-200 bg-emerald-50/40 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="text-xs font-bold uppercase tracking-wider text-emerald-700">
              {t('wholesale.artisan_details', 'Artisan Information')}
            </span>
            <span className="px-2 py-0.5 rounded-full text-[11px] font-bold bg-emerald-100 text-emerald-800 border border-emerald-300">
              Verified
            </span>
          </div>
          <h4 className="text-lg font-bold text-gray-900">
            {artisanName}
          </h4>
          <p className="text-xs sm:text-sm text-gray-600">
            {artisanRegion} · {artisanYears}
          </p>
        </div>

        <div className="text-left sm:text-right border-t sm:border-t-0 border-emerald-200/60 pt-2 sm:pt-0 w-full sm:w-auto">
          <span className="text-xs text-gray-500 block">Artisan ID:</span>
          <span className="font-mono text-sm font-bold text-gray-900 bg-white px-2.5 py-1 rounded border border-gray-300 inline-block shadow-sm">
            {artisanId}
          </span>
        </div>
      </section>

      {/* SECTION 5 — Call to Action Buttons (no-print) */}
      <section id="wholesale-actions" className="no-print pt-4 border-t border-gray-200 flex flex-col sm:flex-row gap-3">
        {/* Download PDF Button */}
        <button
          type="button"
          onClick={onDownloadPdf || (() => window.print())}
          className="flex-1 py-3.5 px-6 rounded-xl border-2 border-gray-800 text-gray-800 hover:bg-gray-100 font-heading font-bold text-sm sm:text-base flex items-center justify-center gap-2 transition-all shadow-sm active:scale-[0.98]"
        >
          <DownloadSimple size={20} weight="bold" />
          <span>{t('wholesale.download_pdf', 'Download as PDF')}</span>
        </button>

        {/* Send Inquiry via WhatsApp */}
        <a
          href={waUrl}
          target="_blank"
          rel="noopener noreferrer"
          className="flex-1 py-3.5 px-6 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-heading font-bold text-sm sm:text-base flex items-center justify-center gap-2 transition-all shadow-md hover:shadow-lg active:scale-[0.98] text-center"
        >
          <WhatsappLogo size={22} weight="fill" />
          <span>{t('wholesale.send_whatsapp', 'Send Inquiry via WhatsApp')}</span>
        </a>
      </section>

      {/* Footer Legal & Traceability Note */}
      <div className="mt-8 pt-4 border-t border-gray-100 flex flex-col sm:flex-row justify-between text-[11px] text-gray-400 gap-2">
        <span>© KarigaarAI B2B Network · Direct Trade with Artisans</span>
        <span>Cryptographically timestamped artisan catalog</span>
      </div>
    </div>
  )
}
